### ISSUE TITLE
Μικρό bug

### ISSUE THREAD

**Issue by Evasilog** [Iptamenos/Connect4#4]
Στην κλάση RandomChoiceAi.java και συγκεκριμένα το:

    do {
            col = r.nextInt(GUI.gameParameters.getCheckersInARow());
    } while (board.checkFullColumn(col));
θα πρέπει να γίνει:

    do {
            col = r.nextInt(GUI.gameParameters.getNumOfColumns());
    } while (board.checkFullColumn(col));

Καθώς το col πρέπει να έχει έναν αριθμό στο εύρος των στηλών (0-6 ή 0-7), ενώ το getCheckersInARow δίνει το εύρος των μαρκών για νίκη (0-4 ή 0-5) και έτσι τοποθετούνται μάρκες μέχρι την 4η ή την 5η στήλη αναλόγως τον τύπο παιχνιδιού

**Comment by chriskormaris** [comment]
Έχει πολύ δίκιο φίλε μου.
Δεν το πρόσεξα το διορθώνω αμέσως.
Πρόσεξες ότι έβαλα και δυνατότητα για Connect-5 έτσι?
Ωραίος!

**Comment by Evasilog** [comment]
Τέλεια!
Ναι, πολύ ωραία η νέα προσθήκη και λειτουργεί εξαιρετικά.
Και όλες οι ''μικρές'' βελτιώσεις στον κώδικα είναι πάρα πολύ καλές και αναδεικνύουν την ποιότητα του έργου!!

**Comment by chriskormaris** [comment]
Να είσαι καλά!

**Comment by chriskormaris** [comment]
Αν θες ρίξε μια ματιά στα άλλα projects που έχω κάνει:
YouTube Programming Project Demos:
https://www.youtube.com/playlist?list=PLV08zt7F7NIhGfG5zGpFeDOvR30Mi6nM2

Google Play Apps:
https://play.google.com/store/apps/developer?id=Christos+Kormaris

**Comment by chriskormaris** [comment]
Καλησπέρα αγαπητέ evasilog,

Πριν 2 χρόνια συζητούσαμε για το Connect-4 που έχω ανεβάσει στο GitHub.
Ρίξε μια ματιά πώς έχει γίνει τώρα.
https://github.com/chriskormaris/Connect4

Επίσης, έφτιαξα ένα καινούριο παιχνίδι Σκάκι εντελώς δικό μου και
χρειάζομαι τη στήριξη σου.
Οπότε αν σου είναι εύκολο βάλε μου ένα star εδώ:
https://github.com/chriskormaris/MyChessGame

Καλή συνέχεια και καλές σπουδές.
Χρήστος Κορμαρής
